-- Use DVD Rental Database

-- Select from one of the table from database

SELECT * FROM film;

-- EXPLAIN 
-- SHOWS THE EXECUTIPON PLAN OF STATEMENT
/*
OPTIONS		DEFAULT 	VALUE

ANALYZE	- 	FALSE		BOOLEAN	
VERBOSE	-	TRUE		BOOLEAN
COSTS	-	TRUE		BOOLEAN
BUFFERS	-	FALSE		BOOLEAN
TIMING	-	TRUE		BOOLEAN
FORMAT	-	TEXT		TEXT | JSON | XML | YAML
*/

EXPLAIN SELECT * FROM film;

-- OUTPUT -> "Seq Scan on film  (cost=0.00..64.00 rows=1000 width=384)"

-- COST- ESTIMATE STARTUP COST
-- COST- (disk pages read * seq_page_cost) + (rows scanned * cpu_tuples_cost)
-- ROWS- NUMBER OF ROWS RETURNED
-- WIDTH- ESTIMATED AVERAGE WIDTH OF THE ROW OUTPUT (BYTES)

SELECT relpages AS "Disk Page Read", reltuples AS "Rows Scanned"
FROM pg_class
WHERE relname = 'film';

-- seq_page_cost - ESTIMATE OF THE COST OF DISK PAGE FETCH, DEFAULT 1
-- cpu_tuples_cost - ESTIMATE OF THE COST OF PROCESSING EACH ROW, DEFAULT 0.01

-- SEQ SCAN (COST IS MUCH HIGHER)
EXPLAIN SELECT * FROM film
WHERE film_id > 40;

-- INDEX SCAN USING PKEY (COST IS MUCH LOWER)
EXPLAIN SELECT * FROM film
WHERE film_id < 40;

EXPLAIN SELECT * FROM film
WHERE film_id < 40 AND rating = 'R';


-- EXPLAIN ANALYZE
-- ACTUALLY RUNS QUERY AND DISPLAY ACTUAL COST AND TIME (PLANNING TIME & EXECUTION TIME)

EXPLAIN ANALYZE 
SELECT * FROM film;

EXPLAIN ANALYZE
SELECT * FROM film
WHERE film_id > 40;

EXPLAIN ANALYZE
SELECT * FROM film
WHERE film_id < 40 AND rating = 'R';

/*
EXPLAIN VERBOSE
	DISPLAYS VARIOUS OPERATIONS HAPPENING AT NODE LEVEL IN QUERY 

EXPLAIN COSTS
	DISPLAY VARIOUS COSTS ASSOCIATED FOR BUILDING QUERY PLAN

EXPLAIN BUFFER
	DISPLAYS STATUS OF MEMOMRY BUFFER IN POSTGRES

EXPLAIN TIMING
	DISPLAYS EXECUTIONS TIME FOR QUERY AND NODE

EXPLAIN FORMAT
	DISPLAYS RESULT IN TEXT OR ANY DIFFERENT FORMAT 
*/